# Generated by Django 5.2.15 on 2026-06-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization/Department Name', max_length=255)),
                ('slug', models.SlugField(help_text="Unique slug for tenant URL routing (e.g. 'anits')", max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Plan (1 CEO, 100 requests/mo)'), ('professional', 'Professional Plan (Multiple CEOs, Unlimited requests)'), ('enterprise', 'Enterprise Plan (Custom, Dedicated support)')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
